// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6oKb-azXcEo3hzLeg-v3T9tzhurMqkKI',
    appId: '1:1038902753284:web:c974260faaa1ad10771d51',
    messagingSenderId: '1038902753284',
    projectId: 'travel-fyp',
    authDomain: 'travel-fyp.firebaseapp.com',
    storageBucket: 'travel-fyp.firebasestorage.app',
    measurementId: 'G-G805GSW8K3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbX6nx_NaHRGTbf1P3iOP_lLL5bPUhZuo',
    appId: '1:1038902753284:android:b4d3c72c7d1f46bc771d51',
    messagingSenderId: '1038902753284',
    projectId: 'travel-fyp',
    storageBucket: 'travel-fyp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0W-o0aEPrAgeYsaBqpYQzT89VCY1wQzI',
    appId: '1:1038902753284:ios:29c64be379132220771d51',
    messagingSenderId: '1038902753284',
    projectId: 'travel-fyp',
    storageBucket: 'travel-fyp.firebasestorage.app',
    iosBundleId: 'com.example.travelPlanningFyp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0W-o0aEPrAgeYsaBqpYQzT89VCY1wQzI',
    appId: '1:1038902753284:ios:29c64be379132220771d51',
    messagingSenderId: '1038902753284',
    projectId: 'travel-fyp',
    storageBucket: 'travel-fyp.firebasestorage.app',
    iosBundleId: 'com.example.travelPlanningFyp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6oKb-azXcEo3hzLeg-v3T9tzhurMqkKI',
    appId: '1:1038902753284:web:d43085c525aacd7c771d51',
    messagingSenderId: '1038902753284',
    projectId: 'travel-fyp',
    authDomain: 'travel-fyp.firebaseapp.com',
    storageBucket: 'travel-fyp.firebasestorage.app',
    measurementId: 'G-Y3VGEDEKPT',
  );
}
